export default {
    facebook_icon: require("../assets/images/ic_facebook.png"),
    google_icon: require("../assets/images/ic_google.png"),
    bgc: require("../assets/images/bgc.png"),
    BACK_ARROW: require('../assets/images/ic_back_arrow.png'),
    Radio_icon: require('../assets/images/radio-icon.png'),
    HamBurger: require("../assets/images/hameburger.png"),
    more_vert: require("../assets/images/more-vert.png"),
    thumb_up: require("../assets/images/thumb-up.png"),
    thumb_down: require("../assets/images/thumb-down.png"),
    comment: require("../assets/images/comment.png"),
    share_icon: require("../assets/images/share-icon.png"),
    post_image: require("../assets/images/postimage.png"),
    post_image2: require("../assets/images/post2.png"),
    delete_icon: require("../assets/images/ic_crss.png"),
    home_icon: require("../assets/images/ic_home.png"),
    profile_icon: require("../assets/images/Profile.png"),
    notification_icon: require("../assets/images/notifications.png"),
    search_icon: require("../assets/images/ic_srch.png"),
    add_icon: require("../assets/images/addicon.png"),
    all_icon: require("../assets/images/allicon.png"),
    video_icon: require("../assets/images/video-icon.png"),
    drop_down_icon: require("../assets/images/dropdown.png")

}